USE raw_it;


--Table to STORE the IMPORT INFORMATION
DROP TABLE AKASH_TEMP_VODAFONE_INGESTION;
CREATE EXTERNAL TABLE AKASH_TEMP_VODAFONE_INGESTION
(
 GROUP_ID STRING,
 ENV_DESC STRING,
 SOURCE_NAME STRING,
 SRC_SCHEMA_NAME STRING,
 TGT_SCHEMA_NAME STRING,
 IMPORT_TYPE STRING,
 SOURCE_CONN_STR STRING,
 SOURCE_DIR STRING,
 SOURCE_TBL STRING,
 TARGET_DIR STRING,
 TARGET_TBL STRING,
 METRIC_SCHEMA_NAME STRING,
 METRIC_TABLE_NAME STRING,
 LIST_OF_TASKS ARRAY<STRING>,
 LIST_OF_PARTITIONS ARRAY<STRING>,
 TABLE_PARTITION_VAL_SOURCE STRING,
 SQOOP_INCR_LOAD_FLG STRING,
 SQOOP_INCR_CHK_COL STRING,
 NO_OF_MAPPERS TINYINT
)
ROW FORMAT DELIMITED
  FIELDS TERMINATED BY '|'
STORED AS TEXTFILE
LOCATION  '/tmp/akash/hivetablestore';


--Sample Query to push records in the above table
INSERT INTO TABLE AKASH_TEMP_VODAFONE_INGESTION
SELECT
'vf_it',
'dev',
'cops',
NULL,
'raw_it',
'file',
NULL,
'path',
NULL,
'path',
'mytable',
'raw_it',
'vf_ingestion_metric',
array('filemerge','ingest'),
array('year','month'),
'data',
NULL,
NULL,
0 ;





--Creating a view on top of AKASH_TEMP_VODAFONE_INGESTION
DROP VIEW AKASH_TEMP_INGESTION_VIEW;
CREATE VIEW AKASH_TEMP_INGESTION_VIEW
COMMENT 'Referrers to  AKASH_TEMP_VODAFONE_INGESTION'
AS
SELECT
COALESCE(GROUP_ID,'null') OPCO,
COALESCE(SOURCE_NAME,'null') DATA_SOURCE,
COALESCE(TARGET_TBL,'null') TABLE,
COALESCE(IMPORT_TYPE,'null') IMPORT_TYPE,
CONCAT_WS
('|',
COALESCE(GROUP_ID,'null'),
COALESCE(ENV_DESC,'null'),
COALESCE(SOURCE_NAME,'null'), 
COALESCE(SRC_SCHEMA_NAME,'null'),
COALESCE(TGT_SCHEMA_NAME,'null'),
COALESCE(IMPORT_TYPE,'null'),
COALESCE(SOURCE_CONN_STR,'null'),
COALESCE(SOURCE_DIR,'null'),
COALESCE(SOURCE_TBL,'null'),
COALESCE(TARGET_DIR,'null'),
COALESCE(TARGET_TBL,'null'),
COALESCE(METRIC_SCHEMA_NAME,'null'),
COALESCE(METRIC_TABLE_NAME,'null'),
CONCAT_WS(',',LIST_OF_TASKS),
CONCAT_WS(',',LIST_OF_PARTITIONS),
COALESCE(TABLE_PARTITION_VAL_SOURCE,'null'),
COALESCE(SQOOP_INCR_LOAD_FLG,'null'),
COALESCE(SQOOP_INCR_CHK_COL,'null'),
COALESCE(NO_OF_MAPPERS,'null')
) QUERY
FROM RAW_IT.AKASH_TEMP_VODAFONE_INGESTION;
